#!/usr/bin/env python3
"""
LightweightMC protocol data generator (Option A).

Reads hand-curated seed JSON from tools/protocol_seed/ and emits committed C++
headers into src/protocol/data/:

  - protocol_versions.h : ProtocolVersionInfo table + resolve()/eraFor()/nearestSupported()
  - packet_ids.h        : per-era S2C/C2S ID arrays indexed by the PacketKind enum,
                          plus fromClientPacketId reverse-lookup tables.

Design goals:
  * Zero external dependencies (Python stdlib only).
  * Deterministic output (sorted, stable formatting) so committed headers never
    churn on regeneration.
  * Adding a new MC version = edit versions.json / packet_ids_*.json and re-run;
    no C++ changes required.

Usage:
  python3 tools/gen_protocol_data.py [--out src/protocol/data]
"""

import argparse
import json
import os
from datetime import datetime, timezone

SEED_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "protocol_seed")

# Canonical PacketKind enum order. MUST stay in sync with include/network/protocol/PacketKind.hpp.
PACKET_KINDS = [
    "DISCONNECT",
    "KEEP_ALIVE",
    "JOIN_GAME",
    "CHAT",
    "ENTITY_EQUIPMENT",
    "SPAWN_POSITION",
    "UPDATE_PLAYER_INFO",
    "PLAYER_POS_LOOK",
    "BLOCK_CHANGE",
    "ANIMATION",
    "ADD_PLAYER",
    "OPEN_WINDOW",
    "WINDOW_ITEMS",
    "SET_SLOT",
    "CONFIRM_TRANSACTION",
    "SCOREBOARD_OBJECTIVE",
    "UPDATE_SCORE",
    "DISPLAY_SCOREBOARD",
    "PLAYER_LIST_HEADER_FOOTER",
    "KEEP_ALIVE_RESPONSE",
    "PLAYER_DIGGING",
    "PLACE_BLOCK",
    "HELD_ITEM",
    "CLICK_WINDOW",
    "CREATIVE_SLOT_ACTION",
]

# Era ordering used for the eraFor() lookup (contiguous protocol ranges).
ERAS = ["LEGACY", "MODERN", "LATEST"]


def load_seed(name):
    path = os.path.join(SEED_DIR, name)
    with open(path, "r") as f:
        return json.load(f)


def build_version_table():
    """Returns entries sorted by protocol: list of (proto, (version, era))."""
    data = load_seed("versions.json")
    rows = []
    for v in data["versions"]:
        proto = int(v["protocol"])
        version = str(v["version"])
        era = v["era"].upper()
        if era not in ERAS:
            raise ValueError(f"Unknown era '{era}' for {version} in versions.json")
        rows.append((proto, version, era))

    # Deduplicate by protocol (some versions share a protocol number).
    seen = {}
    for proto, version, era in rows:
        if proto not in seen:
            seen[proto] = (version, era)
    entries = sorted(seen.items())  # list of (proto, (version, era))

    return entries


def build_packet_id_table():
    """Merges the 1.8 baseline with any per-era override files into a single {era: {'s2c': {...}, 'c2s': {...}}} map."""
    base = load_seed("packet_ids_1.8.json")
    result = {}
    for era in ERAS:
        result[era] = {"s2c": dict(base["s2c"]), "c2s": dict(base["c2s"])}

    # Optional per-era override files (e.g. packet_ids_legacy.json) inherit from the baseline.
    for era in ERAS:
        fname = f"packet_ids_{era.lower()}.json"
        path = os.path.join(SEED_DIR, fname)
        if os.path.exists(path):
            with open(path, "r") as f:
                override = json.load(f)
            result[era]["s2c"].update(override.get("s2c", {}))
            result[era]["c2s"].update(override.get("c2s", {}))

    # Validate all keys against the canonical enum.
    for era, tables in result.items():
        for direction in ("s2c", "c2s"):
            for kind in tables[direction]:
                if kind not in PACKET_KINDS:
                    raise ValueError(f"Unknown PacketKind '{kind}' in {era}/{direction} table")

    return result



def emit_protocol_versions(out_dir, entries):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = []
    lines.append("// AUTO-GENERATED by tools/gen_protocol_data.py -- DO NOT EDIT.")
    lines.append("// Regenerate: python3 tools/gen_protocol_data.py")
    lines.append(f"// Generated: {ts}")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include <cstdint>')
    lines.append('#include <cstddef>')
    lines.append('#include <cstdlib>')
    lines.append("")
    lines.append("namespace LightweightMC::Network::Protocol")
    lines.append("{")
    lines.append("")
    lines.append("    enum class Era : std::uint8_t")
    lines.append("    {")
    for i, era in enumerate(ERAS):
        lines.append(f"        {era} = {i},")
    lines.append(f"        COUNT = {len(ERAS)}")
    lines.append("    };")
    lines.append("")
    lines.append("    inline const char *eraName(Era era)")
    lines.append("    {")
    lines.append("        switch (era)")
    lines.append("        {")
    for era in ERAS:
        lines.append(f'            case Era::{era}: return "{era}";')
    lines.append('            default: return "UNKNOWN";')
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    struct ProtocolVersionInfo")
    lines.append("    {")
    lines.append("        int32_t protocol;")
    lines.append("        const char *version;")
    lines.append("        Era era;")
    lines.append("    };")
    lines.append("")

    # Static table.
    lines.append("    static constexpr ProtocolVersionInfo kProtocolVersions[] = {")
    for proto, (version, era) in entries:
        lines.append(f'        {{ {proto}, "{version}", Era::{era} }},')
    lines.append("    };")
    lines.append("")
    lines.append("    static constexpr std::size_t kProtocolVersionCount = sizeof(kProtocolVersions) / sizeof(kProtocolVersions[0]);")
    lines.append("")

    # resolve(): exact protocol match.
    lines.append("    // Returns a pointer to the matching entry, or nullptr if the protocol is unsupported.")
    lines.append("    inline const ProtocolVersionInfo *resolve(int32_t protocol)")
    lines.append("    {")
    lines.append("        for (std::size_t i = 0; i < kProtocolVersionCount; ++i)")
    lines.append("        {")
    lines.append("            if (kProtocolVersions[i].protocol == protocol)")
    lines.append("                return &kProtocolVersions[i];")
    lines.append("        }")
    lines.append("        return nullptr;")
    lines.append("    }")
    lines.append("")

    # nearestSupported(): closest entry for kick messages.
    lines.append("    // Returns the closest supported version (for kick messages). Never returns nullptr.")
    lines.append("    inline const ProtocolVersionInfo *nearestSupported(int32_t protocol)")
    lines.append("    {")
    lines.append("        if (kProtocolVersionCount == 0) return nullptr;")
    lines.append("        int32_t best = kProtocolVersions[0].protocol;")
    lines.append("        for (std::size_t i = 0; i < kProtocolVersionCount; ++i)")
    lines.append("        {")
    lines.append("            if (std::abs(kProtocolVersions[i].protocol - protocol) < std::abs(best - protocol))")
    lines.append("                best = kProtocolVersions[i].protocol;")
    lines.append("        }")
    lines.append("        return resolve(best);")
    lines.append("    }")
    lines.append("")

    # eraFor(): exact-match first, then nearest-supported fallback (era is not monotonic in protocol number).
    lines.append("    // Maps a protocol number to its era (for adapters). Exact match first, else nearest supported.")
    lines.append("    inline Era eraFor(int32_t protocol)")
    lines.append("    {")
    lines.append("        const ProtocolVersionInfo *info = resolve(protocol);")
    lines.append("        if (!info) info = nearestSupported(protocol);")
    lines.append("        return info ? info->era : Era::LEGACY;")
    lines.append("    }")
    lines.append("")
    lines.append("} // namespace LightweightMC::Network::Protocol")
    lines.append("")

    path = os.path.join(out_dir, "protocol_versions.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path





def emit_packet_ids(out_dir, id_table):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    kind_index = {k: i for i, k in enumerate(PACKET_KINDS)}

    lines = []
    lines.append("// AUTO-GENERATED by tools/gen_protocol_data.py -- DO NOT EDIT.")
    lines.append("// Regenerate: python3 tools/gen_protocol_data.py")
    lines.append(f"// Generated: {ts}")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include <cstdint>')
    lines.append('#include <cstddef>')
    lines.append('#include "network/protocol/PacketKind.hpp"')
    lines.append('#include "protocol/data/protocol_versions.h"')
    lines.append("")
    lines.append("namespace LightweightMC::Network::Protocol")
    lines.append("{")
    lines.append("")

    # S2C and C2S arrays per era, indexed by PacketKind. Unlisted kinds default to -1 (unsupported).
    for direction in ("s2c", "c2s"):
        label = "S2C" if direction == "s2c" else "C2S"
        lines.append(f"    // {label} packet IDs per era, indexed by PacketKind. -1 = not supported in that era.")
        for era in ERAS:
            table = id_table[era][direction]
            arr = [-1] * len(PACKET_KINDS)
            for kind, pid in table.items():
                arr[kind_index[kind]] = int(pid)
            lines.append(f"    static constexpr std::int32_t k{label}_{era}[] = {{")
            for i in range(0, len(arr), 8):
                chunk = arr[i:i + 8]
                names = ", ".join(f"/* {PACKET_KINDS[i + j]} */ {v}" for j, v in enumerate(chunk))
                lines.append(f"        {names},")
            lines.append("    };")
            lines.append("")

    # S2C reverse lookup per era: maps a 1.8 wire ID (the literal IDs used throughout the
    # codebase) to the wire ID in that era. -1 = unknown/unmapped for this era. The index is
    # the 1.8 S2C wire ID, so entries beyond the largest 1.8 ID are not present.
    max_18_id = max((pid for pid in id_table["LEGACY"]["s2c"].values() if pid >= 0), default=0)
    lines.append("    // S2C reverse lookup per era, indexed by the 1.8 wire ID (the literal IDs used")
    lines.append("    // throughout the codebase). -1 = unknown/unmapped for this era.")
    for era in ERAS:
        table = id_table[era]["s2c"]
        arr = [-1] * (max_18_id + 1)
        # For each kind, its 1.8 wire ID is the index and its era wire ID is the value.
        for kind, pid in table.items():
            legacy_pid = id_table["LEGACY"]["s2c"].get(kind, -1)
            if legacy_pid >= 0 and legacy_pid <= max_18_id:
                arr[legacy_pid] = int(pid)
        lines.append(f"    static constexpr std::int32_t kS2CReverse_{era}[] = {{")
        for i in range(0, len(arr), 8):
            chunk = arr[i:i + 8]
            names = ", ".join(f"/* {i + j:02X} */ {v}" for j, v in enumerate(chunk))
            lines.append(f"        {names},")
        lines.append("    };")
        lines.append("")

    # Reverse-lookup tables for C2S dispatch (id -> PacketKind).
    lines.append("    // Reverse lookup: C2S id -> PacketKind (-1 = unknown/ignored). Indexed by raw packet id.")
    for era in ERAS:
        table = id_table[era]["c2s"]
        max_id = max(table.values(), default=0)
        rev = [-1] * (max_id + 1)
        for kind, pid in table.items():
            rev[int(pid)] = kind_index[kind]
        lines.append(f"    static constexpr std::int32_t kC2S_{era}_Reverse[] = {{")
        for i in range(0, len(rev), 16):
            chunk = rev[i:i + 16]
            comma = "," if i + 16 < len(rev) else ""
            lines.append("        " + ", ".join(str(v) for v in chunk) + comma)
        lines.append("    };")
        lines.append("")

    # Helper accessors.
    lines.append("    inline std::int32_t s2cPacketId(Era era, PacketKind kind)")
    lines.append("    {")
    lines.append("        const std::size_t idx = static_cast<std::size_t>(kind);")
    lines.append("        switch (era)")
    lines.append("        {")
    for era in ERAS:
        lines.append(f"            case Era::{era}: return kS2C_{era}[idx];")
    lines.append("            default: return -1;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    // Maps a 1.8 wire ID to the equivalent wire ID in the given era (reverse tables).")
    lines.append("    // Returns -1 if the ID is not mapped for that era.")
    lines.append("    inline std::int32_t s2cWireIdFromLegacy(Era era, std::int32_t legacyWireId)")
    lines.append("    {")
    lines.append("        if (legacyWireId < 0) return -1;")
    lines.append("        switch (era)")
    lines.append("        {")
    for era in ERAS:
        lines.append(f"            case Era::{era}: {{")
        lines.append(f"                if (legacyWireId >= static_cast<std::int32_t>(sizeof(kS2CReverse_{era}) / sizeof(kS2CReverse_{era}[0]))) return -1;")
        lines.append(f"                return kS2CReverse_{era}[legacyWireId];")
        lines.append("            }")
    lines.append("            default: return -1;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    inline PacketKind c2sPacketKind(Era era, std::int32_t id)")
    lines.append("    {")
    lines.append("        switch (era)")
    lines.append("        {")
    for era in ERAS:
        lines.append(f"            case Era::{era}: {{")
        lines.append(f"                if (id < 0 || id >= static_cast<std::int32_t>(sizeof(kC2S_{era}_Reverse) / sizeof(kC2S_{era}_Reverse[0]))) return PacketKind::UNKNOWN;")
        lines.append(f"                const std::int32_t k = kC2S_{era}_Reverse[id];")
        lines.append("                return k < 0 ? PacketKind::UNKNOWN : static_cast<PacketKind>(k);")
        lines.append("            }")
    lines.append("            default: return PacketKind::UNKNOWN;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("} // namespace LightweightMC::Network::Protocol")
    lines.append("")

    path = os.path.join(out_dir, "packet_ids.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path


def main():
    parser = argparse.ArgumentParser(description="LightweightMC protocol data generator")
    parser.add_argument("--out", default=os.path.join("..","include", "protocol", "data"), help="Output directory for generated headers")
    args = parser.parse_args()

    out_dir = args.out
    os.makedirs(out_dir, exist_ok=True)

    entries = build_version_table()
    id_table = build_packet_id_table()

    p1 = emit_protocol_versions(out_dir, entries)
    p2 = emit_packet_ids(out_dir, id_table)

    print(f"[gen_protocol_data] Wrote {p1}")
    print(f"[gen_protocol_data] Wrote {p2}")
    print(f"[gen_protocol_data] {len(entries)} protocol versions, {len(ERAS)} eras.")


if __name__ == "__main__":
    main()
