// AUTO-GENERATED by tools/gen_protocol_data.py -- DO NOT EDIT.
// Regenerate: python3 tools/gen_protocol_data.py
// Generated: 2026-09-25 13:04 UTC
#pragma once

#include <cstdint>
#include <cstddef>
#include "network/protocol/PacketKind.hpp"
#include "protocol/data/protocol_versions.h"

namespace LightweightMC::Network::Protocol
{

    // S2C packet IDs per era, indexed by PacketKind. -1 = not supported in that era.
    static constexpr std::int32_t kS2C_LEGACY[] = {
        /* DISCONNECT */ 0,
        /* KEEP_ALIVE */ 1,
        /* JOIN_GAME */ 1,
        /* CHAT */ 2,
        /* ENTITY_EQUIPMENT */ 4,
        /* SPAWN_POSITION */ 5,
        /* UPDATE_PLAYER_INFO */ 56,
        /* PLAYER_POS_LOOK */ 8,
        /* BLOCK_CHANGE */ 35,
        /* ANIMATION */ 11,
        /* ADD_PLAYER */ 12,
        /* OPEN_WINDOW */ 45,
        /* WINDOW_ITEMS */ 48,
        /* SET_SLOT */ 49,
        /* CONFIRM_TRANSACTION */ 50,
        /* SCOREBOARD_OBJECTIVE */ 59,
        /* UPDATE_SCORE */ 60,
        /* DISPLAY_SCOREBOARD */ 61,
        /* PLAYER_LIST_HEADER_FOOTER */ 71,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ -1,
        /* PLACE_BLOCK */ -1,
        /* HELD_ITEM */ -1,
        /* CLICK_WINDOW */ -1,
        /* CREATIVE_SLOT_ACTION */ -1,
    };

    static constexpr std::int32_t kS2C_MODERN[] = {
        /* DISCONNECT */ 0,
        /* KEEP_ALIVE */ 1,
        /* JOIN_GAME */ 1,
        /* CHAT */ 2,
        /* ENTITY_EQUIPMENT */ 4,
        /* SPAWN_POSITION */ 5,
        /* UPDATE_PLAYER_INFO */ 56,
        /* PLAYER_POS_LOOK */ 8,
        /* BLOCK_CHANGE */ 35,
        /* ANIMATION */ 11,
        /* ADD_PLAYER */ 12,
        /* OPEN_WINDOW */ 45,
        /* WINDOW_ITEMS */ 48,
        /* SET_SLOT */ 49,
        /* CONFIRM_TRANSACTION */ 50,
        /* SCOREBOARD_OBJECTIVE */ 59,
        /* UPDATE_SCORE */ 60,
        /* DISPLAY_SCOREBOARD */ 61,
        /* PLAYER_LIST_HEADER_FOOTER */ 71,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ -1,
        /* PLACE_BLOCK */ -1,
        /* HELD_ITEM */ -1,
        /* CLICK_WINDOW */ -1,
        /* CREATIVE_SLOT_ACTION */ -1,
    };

    static constexpr std::int32_t kS2C_LATEST[] = {
        /* DISCONNECT */ 0,
        /* KEEP_ALIVE */ 1,
        /* JOIN_GAME */ 1,
        /* CHAT */ 2,
        /* ENTITY_EQUIPMENT */ 4,
        /* SPAWN_POSITION */ 5,
        /* UPDATE_PLAYER_INFO */ 56,
        /* PLAYER_POS_LOOK */ 8,
        /* BLOCK_CHANGE */ 35,
        /* ANIMATION */ 11,
        /* ADD_PLAYER */ 12,
        /* OPEN_WINDOW */ 45,
        /* WINDOW_ITEMS */ 48,
        /* SET_SLOT */ 49,
        /* CONFIRM_TRANSACTION */ 50,
        /* SCOREBOARD_OBJECTIVE */ 59,
        /* UPDATE_SCORE */ 60,
        /* DISPLAY_SCOREBOARD */ 61,
        /* PLAYER_LIST_HEADER_FOOTER */ 71,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ -1,
        /* PLACE_BLOCK */ -1,
        /* HELD_ITEM */ -1,
        /* CLICK_WINDOW */ -1,
        /* CREATIVE_SLOT_ACTION */ -1,
    };

    // C2S packet IDs per era, indexed by PacketKind. -1 = not supported in that era.
    static constexpr std::int32_t kC2S_LEGACY[] = {
        /* DISCONNECT */ -1,
        /* KEEP_ALIVE */ 0,
        /* JOIN_GAME */ -1,
        /* CHAT */ 1,
        /* ENTITY_EQUIPMENT */ -1,
        /* SPAWN_POSITION */ -1,
        /* UPDATE_PLAYER_INFO */ -1,
        /* PLAYER_POS_LOOK */ 4,
        /* BLOCK_CHANGE */ -1,
        /* ANIMATION */ 10,
        /* ADD_PLAYER */ -1,
        /* OPEN_WINDOW */ -1,
        /* WINDOW_ITEMS */ -1,
        /* SET_SLOT */ -1,
        /* CONFIRM_TRANSACTION */ -1,
        /* SCOREBOARD_OBJECTIVE */ -1,
        /* UPDATE_SCORE */ -1,
        /* DISPLAY_SCOREBOARD */ -1,
        /* PLAYER_LIST_HEADER_FOOTER */ -1,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ 7,
        /* PLACE_BLOCK */ 8,
        /* HELD_ITEM */ 9,
        /* CLICK_WINDOW */ 14,
        /* CREATIVE_SLOT_ACTION */ 16,
    };

    static constexpr std::int32_t kC2S_MODERN[] = {
        /* DISCONNECT */ -1,
        /* KEEP_ALIVE */ 0,
        /* JOIN_GAME */ -1,
        /* CHAT */ 1,
        /* ENTITY_EQUIPMENT */ -1,
        /* SPAWN_POSITION */ -1,
        /* UPDATE_PLAYER_INFO */ -1,
        /* PLAYER_POS_LOOK */ 4,
        /* BLOCK_CHANGE */ -1,
        /* ANIMATION */ 10,
        /* ADD_PLAYER */ -1,
        /* OPEN_WINDOW */ -1,
        /* WINDOW_ITEMS */ -1,
        /* SET_SLOT */ -1,
        /* CONFIRM_TRANSACTION */ -1,
        /* SCOREBOARD_OBJECTIVE */ -1,
        /* UPDATE_SCORE */ -1,
        /* DISPLAY_SCOREBOARD */ -1,
        /* PLAYER_LIST_HEADER_FOOTER */ -1,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ 7,
        /* PLACE_BLOCK */ 8,
        /* HELD_ITEM */ 9,
        /* CLICK_WINDOW */ 14,
        /* CREATIVE_SLOT_ACTION */ 16,
    };

    static constexpr std::int32_t kC2S_LATEST[] = {
        /* DISCONNECT */ -1,
        /* KEEP_ALIVE */ 0,
        /* JOIN_GAME */ -1,
        /* CHAT */ 1,
        /* ENTITY_EQUIPMENT */ -1,
        /* SPAWN_POSITION */ -1,
        /* UPDATE_PLAYER_INFO */ -1,
        /* PLAYER_POS_LOOK */ 4,
        /* BLOCK_CHANGE */ -1,
        /* ANIMATION */ 10,
        /* ADD_PLAYER */ -1,
        /* OPEN_WINDOW */ -1,
        /* WINDOW_ITEMS */ -1,
        /* SET_SLOT */ -1,
        /* CONFIRM_TRANSACTION */ -1,
        /* SCOREBOARD_OBJECTIVE */ -1,
        /* UPDATE_SCORE */ -1,
        /* DISPLAY_SCOREBOARD */ -1,
        /* PLAYER_LIST_HEADER_FOOTER */ -1,
        /* KEEP_ALIVE_RESPONSE */ -1,
        /* PLAYER_DIGGING */ 7,
        /* PLACE_BLOCK */ 8,
        /* HELD_ITEM */ 9,
        /* CLICK_WINDOW */ 14,
        /* CREATIVE_SLOT_ACTION */ 16,
    };

    // S2C reverse lookup per era, indexed by the 1.8 wire ID (the literal IDs used
    // throughout the codebase). -1 = unknown/unmapped for this era.
    static constexpr std::int32_t kS2CReverse_LEGACY[] = {
        /* 00 */ 0,
        /* 01 */ 1,
        /* 02 */ 2,
        /* 03 */ -1,
        /* 04 */ 4,
        /* 05 */ 5,
        /* 06 */ -1,
        /* 07 */ -1,
        /* 08 */ 8,
        /* 09 */ -1,
        /* 0A */ -1,
        /* 0B */ 11,
        /* 0C */ 12,
        /* 0D */ -1,
        /* 0E */ -1,
        /* 0F */ -1,
        /* 10 */ -1,
        /* 11 */ -1,
        /* 12 */ -1,
        /* 13 */ -1,
        /* 14 */ -1,
        /* 15 */ -1,
        /* 16 */ -1,
        /* 17 */ -1,
        /* 18 */ -1,
        /* 19 */ -1,
        /* 1A */ -1,
        /* 1B */ -1,
        /* 1C */ -1,
        /* 1D */ -1,
        /* 1E */ -1,
        /* 1F */ -1,
        /* 20 */ -1,
        /* 21 */ -1,
        /* 22 */ -1,
        /* 23 */ 35,
        /* 24 */ -1,
        /* 25 */ -1,
        /* 26 */ -1,
        /* 27 */ -1,
        /* 28 */ -1,
        /* 29 */ -1,
        /* 2A */ -1,
        /* 2B */ -1,
        /* 2C */ -1,
        /* 2D */ 45,
        /* 2E */ -1,
        /* 2F */ -1,
        /* 30 */ 48,
        /* 31 */ 49,
        /* 32 */ 50,
        /* 33 */ -1,
        /* 34 */ -1,
        /* 35 */ -1,
        /* 36 */ -1,
        /* 37 */ -1,
        /* 38 */ 56,
        /* 39 */ -1,
        /* 3A */ -1,
        /* 3B */ 59,
        /* 3C */ 60,
        /* 3D */ 61,
        /* 3E */ -1,
        /* 3F */ -1,
        /* 40 */ -1,
        /* 41 */ -1,
        /* 42 */ -1,
        /* 43 */ -1,
        /* 44 */ -1,
        /* 45 */ -1,
        /* 46 */ -1,
        /* 47 */ 71,
    };

    static constexpr std::int32_t kS2CReverse_MODERN[] = {
        /* 00 */ 0,
        /* 01 */ 1,
        /* 02 */ 2,
        /* 03 */ -1,
        /* 04 */ 4,
        /* 05 */ 5,
        /* 06 */ -1,
        /* 07 */ -1,
        /* 08 */ 8,
        /* 09 */ -1,
        /* 0A */ -1,
        /* 0B */ 11,
        /* 0C */ 12,
        /* 0D */ -1,
        /* 0E */ -1,
        /* 0F */ -1,
        /* 10 */ -1,
        /* 11 */ -1,
        /* 12 */ -1,
        /* 13 */ -1,
        /* 14 */ -1,
        /* 15 */ -1,
        /* 16 */ -1,
        /* 17 */ -1,
        /* 18 */ -1,
        /* 19 */ -1,
        /* 1A */ -1,
        /* 1B */ -1,
        /* 1C */ -1,
        /* 1D */ -1,
        /* 1E */ -1,
        /* 1F */ -1,
        /* 20 */ -1,
        /* 21 */ -1,
        /* 22 */ -1,
        /* 23 */ 35,
        /* 24 */ -1,
        /* 25 */ -1,
        /* 26 */ -1,
        /* 27 */ -1,
        /* 28 */ -1,
        /* 29 */ -1,
        /* 2A */ -1,
        /* 2B */ -1,
        /* 2C */ -1,
        /* 2D */ 45,
        /* 2E */ -1,
        /* 2F */ -1,
        /* 30 */ 48,
        /* 31 */ 49,
        /* 32 */ 50,
        /* 33 */ -1,
        /* 34 */ -1,
        /* 35 */ -1,
        /* 36 */ -1,
        /* 37 */ -1,
        /* 38 */ 56,
        /* 39 */ -1,
        /* 3A */ -1,
        /* 3B */ 59,
        /* 3C */ 60,
        /* 3D */ 61,
        /* 3E */ -1,
        /* 3F */ -1,
        /* 40 */ -1,
        /* 41 */ -1,
        /* 42 */ -1,
        /* 43 */ -1,
        /* 44 */ -1,
        /* 45 */ -1,
        /* 46 */ -1,
        /* 47 */ 71,
    };

    static constexpr std::int32_t kS2CReverse_LATEST[] = {
        /* 00 */ 0,
        /* 01 */ 1,
        /* 02 */ 2,
        /* 03 */ -1,
        /* 04 */ 4,
        /* 05 */ 5,
        /* 06 */ -1,
        /* 07 */ -1,
        /* 08 */ 8,
        /* 09 */ -1,
        /* 0A */ -1,
        /* 0B */ 11,
        /* 0C */ 12,
        /* 0D */ -1,
        /* 0E */ -1,
        /* 0F */ -1,
        /* 10 */ -1,
        /* 11 */ -1,
        /* 12 */ -1,
        /* 13 */ -1,
        /* 14 */ -1,
        /* 15 */ -1,
        /* 16 */ -1,
        /* 17 */ -1,
        /* 18 */ -1,
        /* 19 */ -1,
        /* 1A */ -1,
        /* 1B */ -1,
        /* 1C */ -1,
        /* 1D */ -1,
        /* 1E */ -1,
        /* 1F */ -1,
        /* 20 */ -1,
        /* 21 */ -1,
        /* 22 */ -1,
        /* 23 */ 35,
        /* 24 */ -1,
        /* 25 */ -1,
        /* 26 */ -1,
        /* 27 */ -1,
        /* 28 */ -1,
        /* 29 */ -1,
        /* 2A */ -1,
        /* 2B */ -1,
        /* 2C */ -1,
        /* 2D */ 45,
        /* 2E */ -1,
        /* 2F */ -1,
        /* 30 */ 48,
        /* 31 */ 49,
        /* 32 */ 50,
        /* 33 */ -1,
        /* 34 */ -1,
        /* 35 */ -1,
        /* 36 */ -1,
        /* 37 */ -1,
        /* 38 */ 56,
        /* 39 */ -1,
        /* 3A */ -1,
        /* 3B */ 59,
        /* 3C */ 60,
        /* 3D */ 61,
        /* 3E */ -1,
        /* 3F */ -1,
        /* 40 */ -1,
        /* 41 */ -1,
        /* 42 */ -1,
        /* 43 */ -1,
        /* 44 */ -1,
        /* 45 */ -1,
        /* 46 */ -1,
        /* 47 */ 71,
    };

    // Reverse lookup: C2S id -> PacketKind (-1 = unknown/ignored). Indexed by raw packet id.
    static constexpr std::int32_t kC2S_LEGACY_Reverse[] = {
        1, 3, -1, -1, 7, -1, -1, 20, 21, 22, 9, -1, -1, -1, 23, -1,
        24};

    static constexpr std::int32_t kC2S_MODERN_Reverse[] = {
        1, 3, -1, -1, 7, -1, -1, 20, 21, 22, 9, -1, -1, -1, 23, -1,
        24};

    static constexpr std::int32_t kC2S_LATEST_Reverse[] = {
        1, 3, -1, -1, 7, -1, -1, 20, 21, 22, 9, -1, -1, -1, 23, -1,
        24};

    inline std::int32_t s2cPacketId(Era era, PacketKind kind)
    {
        const std::size_t idx = static_cast<std::size_t>(kind);
        switch (era)
        {
        case Era::LEGACY:
            return kS2C_LEGACY[idx];
        case Era::MODERN:
            return kS2C_MODERN[idx];
        case Era::LATEST:
            return kS2C_LATEST[idx];
        default:
            return -1;
        }
    }

    // Maps a 1.8 wire ID to the equivalent wire ID in the given era (reverse tables).
    // Returns -1 if the ID is not mapped for that era.
    inline std::int32_t s2cWireIdFromLegacy(Era era, std::int32_t legacyWireId)
    {
        if (legacyWireId < 0)
            return -1;
        switch (era)
        {
        case Era::LEGACY:
        {
            if (legacyWireId >= static_cast<std::int32_t>(sizeof(kS2CReverse_LEGACY) / sizeof(kS2CReverse_LEGACY[0])))
                return -1;
            return kS2CReverse_LEGACY[legacyWireId];
        }
        case Era::MODERN:
        {
            if (legacyWireId >= static_cast<std::int32_t>(sizeof(kS2CReverse_MODERN) / sizeof(kS2CReverse_MODERN[0])))
                return -1;
            return kS2CReverse_MODERN[legacyWireId];
        }
        case Era::LATEST:
        {
            if (legacyWireId >= static_cast<std::int32_t>(sizeof(kS2CReverse_LATEST) / sizeof(kS2CReverse_LATEST[0])))
                return -1;
            return kS2CReverse_LATEST[legacyWireId];
        }
        default:
            return -1;
        }
    }

    inline PacketKind c2sPacketKind(Era era, std::int32_t id)
    {
        switch (era)
        {
        case Era::LEGACY:
        {
            if (id < 0 || id >= static_cast<std::int32_t>(sizeof(kC2S_LEGACY_Reverse) / sizeof(kC2S_LEGACY_Reverse[0])))
                return PacketKind::UNKNOWN;
            const std::int32_t k = kC2S_LEGACY_Reverse[id];
            return k < 0 ? PacketKind::UNKNOWN : static_cast<PacketKind>(k);
        }
        case Era::MODERN:
        {
            if (id < 0 || id >= static_cast<std::int32_t>(sizeof(kC2S_MODERN_Reverse) / sizeof(kC2S_MODERN_Reverse[0])))
                return PacketKind::UNKNOWN;
            const std::int32_t k = kC2S_MODERN_Reverse[id];
            return k < 0 ? PacketKind::UNKNOWN : static_cast<PacketKind>(k);
        }
        case Era::LATEST:
        {
            if (id < 0 || id >= static_cast<std::int32_t>(sizeof(kC2S_LATEST_Reverse) / sizeof(kC2S_LATEST_Reverse[0])))
                return PacketKind::UNKNOWN;
            const std::int32_t k = kC2S_LATEST_Reverse[id];
            return k < 0 ? PacketKind::UNKNOWN : static_cast<PacketKind>(k);
        }
        default:
            return PacketKind::UNKNOWN;
        }
    }

} // namespace LightweightMC::Network::Protocol
