// AUTO-GENERATED by tools/gen_protocol_data.py -- DO NOT EDIT.
// Regenerate: python3 tools/gen_protocol_data.py
// Generated: 2026-09-25 13:04 UTC
#pragma once

#include <cstdint>
#include <cstddef>
#include <cstdlib>

namespace LightweightMC::Network::Protocol
{

    enum class Era : std::uint8_t
    {
        LEGACY = 0,
        MODERN = 1,
        LATEST = 2,
        COUNT = 3
    };

    inline const char *eraName(Era era)
    {
        switch (era)
        {
        case Era::LEGACY:
            return "LEGACY";
        case Era::MODERN:
            return "MODERN";
        case Era::LATEST:
            return "LATEST";
        default:
            return "UNKNOWN";
        }
    }

    struct ProtocolVersionInfo
    {
        int32_t protocol;
        const char *version;
        Era era;
    };

    static constexpr ProtocolVersionInfo kProtocolVersions[] = {
        {5, "1.7.10", Era::LEGACY},
        {47, "1.8", Era::LEGACY},
        {107, "1.9", Era::MODERN},
        {110, "1.9.4", Era::MODERN},
        {210, "1.10", Era::MODERN},
        {216, "1.11", Era::MODERN},
        {217, "1.11.1", Era::MODERN},
        {335, "1.12", Era::LEGACY},
        {338, "1.12.1", Era::LEGACY},
        {340, "1.12.2", Era::LEGACY},
        {393, "1.13", Era::MODERN},
        {394, "1.13.1", Era::MODERN},
        {397, "1.13.2", Era::MODERN},
        {491, "1.14", Era::MODERN},
        {575, "1.15", Era::MODERN},
        {578, "1.15.2", Era::MODERN},
        {736, "1.16", Era::MODERN},
        {737, "1.16.1", Era::MODERN},
        {751, "1.16.2", Era::MODERN},
        {753, "1.16.3", Era::MODERN},
        {754, "1.16.4", Era::MODERN},
        {755, "1.17", Era::MODERN},
        {756, "1.17.1", Era::MODERN},
        {757, "1.18", Era::MODERN},
        {758, "1.18.1", Era::MODERN},
        {759, "1.18.2", Era::MODERN},
        {760, "1.19", Era::MODERN},
        {762, "1.19.1", Era::MODERN},
        {764, "1.19.3", Era::MODERN},
        {765, "1.19.4", Era::MODERN},
        {766, "1.20", Era::MODERN},
        {769, "1.20.2", Era::MODERN},
    };

    static constexpr std::size_t kProtocolVersionCount = sizeof(kProtocolVersions) / sizeof(kProtocolVersions[0]);

    // Returns a pointer to the matching entry, or nullptr if the protocol is unsupported.
    inline const ProtocolVersionInfo *resolve(int32_t protocol)
    {
        for (std::size_t i = 0; i < kProtocolVersionCount; ++i)
        {
            if (kProtocolVersions[i].protocol == protocol)
                return &kProtocolVersions[i];
        }
        return nullptr;
    }

    // Returns the closest supported version (for kick messages). Never returns nullptr.
    inline const ProtocolVersionInfo *nearestSupported(int32_t protocol)
    {
        if (kProtocolVersionCount == 0)
            return nullptr;
        int32_t best = kProtocolVersions[0].protocol;
        for (std::size_t i = 0; i < kProtocolVersionCount; ++i)
        {
            if (std::abs(kProtocolVersions[i].protocol - protocol) < std::abs(best - protocol))
                best = kProtocolVersions[i].protocol;
        }
        return resolve(best);
    }

    // Maps a protocol number to its era (for adapters). Exact match first, else nearest supported.
    inline Era eraFor(int32_t protocol)
    {
        const ProtocolVersionInfo *info = resolve(protocol);
        if (!info)
            info = nearestSupported(protocol);
        return info ? info->era : Era::LEGACY;
    }

} // namespace LightweightMC::Network::Protocol
